"use client";

import { useEffect, useState } from "react";
import { GraduationCap, MapPin, ShieldCheck, UserRound } from "lucide-react";
import { api } from "@/src/lib/api";
import type { CitizenProfile, Document, Education } from "@/src/types";
import { ErrorState, LoadingState, EmptyState } from "@/components/ui/data-state";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

function Detail({ label, value }: { label: string; value: string | null }) { return <div><dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 text-sm text-foreground">{value || "Not provided"}</dd></div>; }

export function ProfileContent() {
  const [data, setData] = useState<{ profile: CitizenProfile; education: Education[]; documents: Document[] }>();
  const [error, setError] = useState(false);
  useEffect(() => { Promise.all([api.getProfile(), api.getEducation(), api.getDocuments()]).then(([profile, education, documents]) => setData({ profile, education, documents })).catch(() => setError(true)); }, []);
  if (error) return <ErrorState>Profile information is unavailable. Start the demo API and refresh.</ErrorState>;
  if (!data) return <LoadingState label="Loading your profile…" />;
  return <div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><UserRound className="size-4 text-primary" aria-hidden="true" />Personal information</CardTitle></CardHeader><CardContent><dl className="grid gap-5 sm:grid-cols-2"><Detail label="Full name" value={data.profile.full_name} /><Detail label="Date of birth" value={data.profile.date_of_birth} /><Detail label="Gender" value={data.profile.gender} /><Detail label="Category" value={data.profile.category} /><Detail label="Nationality" value={data.profile.nationality} /><Detail label="Email" value={data.profile.email} /></dl></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><MapPin className="size-4 text-primary" aria-hidden="true" />Address</CardTitle></CardHeader><CardContent>{data.profile.addresses.length === 0 ? <EmptyState>No address is available.</EmptyState> : <div className="grid gap-5 sm:grid-cols-2">{data.profile.addresses.map((address) => <section key={address.id}><h3 className="text-sm font-medium">{address.type.toLowerCase()} address</h3><address className="mt-2 not-italic text-sm leading-6 text-muted-foreground">{address.line1}{address.line2 ? `, ${address.line2}` : ""}<br />{address.city}, {address.district}<br />{address.state} — {address.pincode}</address></section>)}</div>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><GraduationCap className="size-4 text-primary" aria-hidden="true" />Education</CardTitle></CardHeader><CardContent>{data.education.length === 0 ? <EmptyState>No education records are available.</EmptyState> : <ul className="space-y-4">{data.education.map((item) => <li key={item.id} className="border-b border-border pb-4 last:border-0 last:pb-0"><p className="font-medium">{item.level}</p><p className="text-sm text-muted-foreground">{item.institution} · {item.board_or_university}</p><p className="mt-1 text-xs text-muted-foreground">{item.year}{item.marks_or_percentage ? ` · ${item.marks_or_percentage}` : ""}</p></li>)}</ul>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-4 text-primary" aria-hidden="true" />Documents</CardTitle></CardHeader><CardContent>{data.documents.length === 0 ? <EmptyState>No documents are available.</EmptyState> : <ul className="space-y-3">{data.documents.map((document) => <li key={document.id} className="flex items-center justify-between gap-3"><div><p className="text-sm font-medium">{document.name}</p><p className="text-xs text-muted-foreground">{document.document_type.replaceAll("_", " ")}</p></div><span className="rounded-full bg-muted px-2 py-1 text-xs text-muted-foreground">{document.source === "DIGILOCKER" ? "Mock DigiLocker" : "Profile"}</span></li>)}</ul>}</CardContent></Card></div>;
}
