"use client";

import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { api } from "@/src/lib/api";
import type { CitizenProfile, Document, Education } from "@/src/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ErrorState, LoadingState } from "@/components/ui/data-state";

type Section = "personal" | "contact" | "family" | "social" | "education" | "general";
const fields: Record<Section, Array<keyof CitizenProfile>> = { personal: ["full_name", "date_of_birth", "gender", "nationality", "marital_status"], contact: ["mobile", "alternate_mobile", "email"], family: ["father_name", "mother_name", "guardian_name", "guardian_relationship"], social: ["category", "ews_status", "disability_status", "ex_serviceman_status", "minority_status"], education: ["highest_qualification", "current_education_status", "current_course", "current_institution"], general: ["employment_status", "occupation", "annual_family_income_range", "preferred_language"] };
const labels: Record<string, string> = { full_name:"Full Name", date_of_birth:"Date of Birth", gender:"Gender", nationality:"Nationality", marital_status:"Marital Status", mobile:"Primary Mobile Number", alternate_mobile:"Alternate Mobile Number", email:"Email Address", father_name:"Father's Name", mother_name:"Mother's Name", guardian_name:"Guardian Name", guardian_relationship:"Guardian Relationship", category:"Category", ews_status:"EWS Status", disability_status:"Person with Disability (PwD)", ex_serviceman_status:"Ex-Serviceman Status", minority_status:"Minority Status", highest_qualification:"Highest Qualification", current_education_status:"Current Education Status", current_course:"Current Course", current_institution:"Current Institution", employment_status:"Employment Status", occupation:"Occupation", annual_family_income_range:"Annual Family Income Range", preferred_language:"Preferred Language" };
const options: Record<string, string[]> = { gender:["Male","Female","Other","Prefer not to say"], nationality:["Indian"], marital_status:["Unmarried","Married","Other"], guardian_relationship:["Parent","Relative","Other"], category:["General","OBC","SC","ST"], ews_status:["Yes","No","Not Applicable"], disability_status:["Yes","No"], ex_serviceman_status:["Yes","No"], minority_status:["Yes","No","Prefer not to say"], highest_qualification:["Below Class 10","Class 10","Class 12","Diploma","Undergraduate","Graduate","Postgraduate","Doctorate","Other"], current_education_status:["School Student","College Student","University Student","Pursuing Diploma","Pursuing Undergraduate","Pursuing Postgraduate","Completed Education","Not Currently Studying","Other"], employment_status:["Student","Employed","Self-employed","Unemployed","Other"], annual_family_income_range:["Below ₹1 lakh","₹1–2.5 lakh","₹2.5–5 lakh","₹5–8 lakh","Above ₹8 lakh","Prefer not to specify"], preferred_language:["English","Hindi","Tamil"] };
const schema = z.object({ full_name:z.string().min(1).optional(), email:z.string().email().optional().or(z.literal("")), mobile:z.string().regex(/^[6-9]\d{9}$/).optional().or(z.literal("")), alternate_mobile:z.string().regex(/^[6-9]\d{9}$/).optional().or(z.literal("")) }).passthrough();

function EditableCard({ title, section, profile, onSave }: { title:string; section:Section; profile:CitizenProfile; onSave:(values:Partial<CitizenProfile>)=>Promise<void> }) {
  const [editing,setEditing]=useState(false); const form=useForm({ resolver:zodResolver(schema) as never, defaultValues:profile }); const activeStudy=String(form.watch("current_education_status")||"").includes("Student")||String(form.watch("current_education_status")||"").startsWith("Pursuing");
  const keys=fields[section].filter(key=>section!=="education"||activeStudy||!["current_course","current_institution"].includes(key));
  return <Card><CardHeader className="flex-row items-center justify-between"><CardTitle>{title}</CardTitle><Button variant="outline" onClick={()=>{form.reset(profile);setEditing(!editing)}}>{editing?"Cancel":"Edit"}</Button></CardHeader><CardContent>{editing?<form className="grid gap-3 sm:grid-cols-2" onSubmit={form.handleSubmit(async values=>{await onSave(Object.fromEntries(fields[section].map(key=>[key,values[key]])));setEditing(false);})}>{keys.map(key=>options[key]?<div key={key}><Label>{labels[key]}</Label><Select selectedKey={String(form.watch(key)||"")} onSelectionChange={value=>form.setValue(key,String(value))}><SelectTrigger><SelectValue>{String(form.watch(key)||"Select an option")}</SelectValue></SelectTrigger><SelectContent>{options[key].map(value=><SelectItem id={value} key={value}>{value}</SelectItem>)}</SelectContent></Select></div>:<div key={key}><Label htmlFor={key}>{labels[key]}</Label><Input id={key} type={key==="date_of_birth"?"date":key.includes("mobile")?"tel":"text"} {...form.register(key)} />{form.formState.errors[key]?.message&&<p className="text-xs text-destructive">{String(form.formState.errors[key]?.message)}</p>}</div>)}<Button type="submit" isDisabled={form.formState.isSubmitting}>{form.formState.isSubmitting?"Saving…":"Save Changes"}</Button></form>:<dl className="grid gap-3 sm:grid-cols-2">{keys.map(key=><div key={key}><dt className="text-xs text-muted-foreground">{labels[key]}</dt><dd>{String(profile[key]||"Not provided")}</dd></div>)}</dl>}</CardContent></Card>
}

export function ProfileContent(){const [data,setData]=useState<{profile:CitizenProfile;education:Education[];documents:Document[]}>();const [error,setError]=useState(false);const [notice,setNotice]=useState("");const refresh=()=>Promise.all([api.getProfile(),api.getEducation(),api.getDocuments()]).then(([profile,education,documents])=>setData({profile,education,documents}));useEffect(()=>{refresh().catch(()=>setError(true))},[]);if(error)return <ErrorState>We couldn&apos;t load your profile.</ErrorState>;if(!data)return <LoadingState label="Loading profile…"/>;const save=async(values:Partial<CitizenProfile>)=>{try{const profile=await api.updateProfile(values);setData({...data,profile});setNotice("Profile updated")}catch{setNotice("Could not save profile. Please try again.")}};return <div className="grid gap-5 xl:grid-cols-2">{notice&&<p role="status" className="xl:col-span-2 rounded bg-muted p-3">{notice}</p>}<EditableCard title="Personal Details" section="personal" profile={data.profile} onSave={save}/><EditableCard title="Contact Details" section="contact" profile={data.profile} onSave={save}/><EditableCard title="Family Details" section="family" profile={data.profile} onSave={save}/><EditableCard title="Social / Reservation Details" section="social" profile={data.profile} onSave={save}/><EditableCard title="Basic Education" section="education" profile={data.profile} onSave={save}/><EditableCard title="Other General Details" section="general" profile={data.profile} onSave={save}/></div>}
