export const chatbotUi = {
  en: { assistant: "Assistant", openAssistant: "Open assistant", closeAssistant: "Close assistant", askGovernmentService: "Ask about a government service", send: "Send", chatWelcome: "Hello. I can help you find and understand government services.", chatThinking: "Thinking…", chatError: "Something went wrong while processing your request. Please try again.", chatPromptIncome: "How do I get an income certificate?", chatPromptKisan: "Tell me about PM-KISAN" },
  hi: { assistant: "सहायक", openAssistant: "सहायक खोलें", closeAssistant: "सहायक बंद करें", askGovernmentService: "सरकारी सेवा के बारे में पूछें", send: "भेजें", chatWelcome: "नमस्ते। मैं सरकारी सेवाएँ खोजने और समझने में आपकी मदद कर सकता हूँ।", chatThinking: "सोच रहा है…", chatError: "आपके अनुरोध को संसाधित करते समय कुछ गड़बड़ हुई। कृपया फिर से प्रयास करें।", chatPromptIncome: "आय प्रमाणपत्र कैसे प्राप्त करें?", chatPromptKisan: "मुझे पीएम-किसान के बारे में बताएं" },
  mr: { assistant: "सहाय्यक", openAssistant: "सहाय्यक उघडा", closeAssistant: "सहाय्यक बंद करा", askGovernmentService: "सरकारी सेवेबद्दल विचारा", send: "पाठवा", chatWelcome: "नमस्कार. सरकारी सेवा शोधण्यात आणि समजून घेण्यात मी मदत करू शकतो.", chatThinking: "विचार करत आहे…", chatError: "तुमच्या विनंतीवर प्रक्रिया करताना काहीतरी चूक झाली. पुन्हा प्रयत्न करा.", chatPromptIncome: "उत्पन्न प्रमाणपत्र कसे मिळवायचे?", chatPromptKisan: "पीएम-किसानबद्दल सांगा" },
  kn: { assistant: "ಸಹಾಯಕ", openAssistant: "ಸಹಾಯಕ ತೆರೆಯಿರಿ", closeAssistant: "ಸಹಾಯಕ ಮುಚ್ಚಿ", askGovernmentService: "ಸರ್ಕಾರಿ ಸೇವೆಯ ಬಗ್ಗೆ ಕೇಳಿ", send: "ಕಳುಹಿಸಿ", chatWelcome: "ನಮಸ್ಕಾರ. ಸರ್ಕಾರಿ ಸೇವೆಗಳನ್ನು ಹುಡುಕಲು ಮತ್ತು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ನಾನು ಸಹಾಯ ಮಾಡಬಹುದು.", chatThinking: "ಯೋಚಿಸಲಾಗುತ್ತಿದೆ…", chatError: "ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುವಾಗ ಸಮಸ್ಯೆಯಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", chatPromptIncome: "ಆದಾಯ ಪ್ರಮಾಣಪತ್ರವನ್ನು ಹೇಗೆ ಪಡೆಯುವುದು?", chatPromptKisan: "ಪಿಎಂ-ಕಿಸಾನ್ ಬಗ್ಗೆ ತಿಳಿಸಿ" },
  ta: { assistant: "உதவியாளர்", openAssistant: "உதவியாளரைத் திறக்கவும்", closeAssistant: "உதவியாளரை மூடவும்", askGovernmentService: "அரசுச் சேவை பற்றி கேளுங்கள்", send: "அனுப்பு", chatWelcome: "வணக்கம். அரசுச் சேவைகளைக் கண்டறிந்து புரிந்துகொள்ள நான் உதவ முடியும்.", chatThinking: "சிந்திக்கிறது…", chatError: "உங்கள் கோரிக்கையைச் செயல்படுத்துவதில் சிக்கல் ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.", chatPromptIncome: "வருமானச் சான்றிதழ் எப்படிப் பெறுவது?", chatPromptKisan: "பிஎம்-கிசான் பற்றி சொல்லுங்கள்" },
  te: { assistant: "సహాయకుడు", openAssistant: "సహాయకుడిని తెరవండి", closeAssistant: "సహాయకుడిని మూసివేయండి", askGovernmentService: "ప్రభుత్వ సేవ గురించి అడగండి", send: "పంపండి", chatWelcome: "నమస్కారం. ప్రభుత్వ సేవలను కనుగొని అర్థం చేసుకోవడంలో నేను సహాయం చేయగలను.", chatThinking: "ఆలోచిస్తోంది…", chatError: "మీ అభ్యర్థనను ప్రాసెస్ చేయడంలో సమస్య ఏర్పడింది. మళ్లీ ప్రయత్నించండి.", chatPromptIncome: "ఆదాయ ధృవీకరణ పత్రం ఎలా పొందాలి?", chatPromptKisan: "పీఎం-కిసాన్ గురించి చెప్పండి" },
  bn: { assistant: "সহায়ক", openAssistant: "সহায়ক খুলুন", closeAssistant: "সহায়ক বন্ধ করুন", askGovernmentService: "সরকারি পরিষেবা সম্পর্কে জিজ্ঞাসা করুন", send: "পাঠান", chatWelcome: "নমস্কার। সরকারি পরিষেবা খুঁজে বুঝতে আমি সাহায্য করতে পারি।", chatThinking: "ভাবছি…", chatError: "আপনার অনুরোধ প্রক্রিয়া করতে সমস্যা হয়েছে। আবার চেষ্টা করুন।", chatPromptIncome: "আয়ের শংসাপত্র কীভাবে পাব?", chatPromptKisan: "পিএম-কিষাণ সম্পর্কে বলুন" },
} as const;

export const phase2ChatbotUi = {
  en: { startingApplication: "Starting application…", applyForService: "Apply for {name}", applicationStartedMessage: "Your application has been started. Here is what it still needs.", applicationResumedMessage: "I found your existing draft and resumed it.", applicationProgress: "Application progress", applicationInProgress: "Application in progress", profileInformation: "Profile information", completeStatus: "Complete", pendingStatus: "Pending", readyStatus: "Ready", notReadyStatus: "Not ready", missingCount: "{count} missing", noPaymentRequired: "No payment required", nextStage: "Next: {stage}", stagePROFILE: "Profile", stageADDITIONAL_INFORMATION: "Additional information", stageDOCUMENTS: "Documents", stageCONSENT: "Consent", stageREVIEW: "Review", stagePAYMENT: "Payment", stageSUBMISSION: "Submission", stageCOMPLETE: "Complete" },
  hi: { startingApplication: "आवेदन शुरू हो रहा है…", applyForService: "{name} के लिए आवेदन करें", applicationStartedMessage: "आपका आवेदन शुरू हो गया है। अभी आवश्यक चीज़ें नीचे हैं।", applicationResumedMessage: "मुझे आपका मौजूदा मसौदा मिला और मैंने उसे फिर से शुरू किया।", applicationProgress: "आवेदन की प्रगति", applicationInProgress: "आवेदन प्रगति पर है", profileInformation: "प्रोफ़ाइल जानकारी", completeStatus: "पूर्ण", pendingStatus: "लंबित", readyStatus: "तैयार", notReadyStatus: "तैयार नहीं", missingCount: "{count} बाकी", noPaymentRequired: "भुगतान आवश्यक नहीं", nextStage: "अगला: {stage}", stagePROFILE: "प्रोफ़ाइल", stageADDITIONAL_INFORMATION: "अतिरिक्त जानकारी", stageDOCUMENTS: "दस्तावेज़", stageCONSENT: "सहमति", stageREVIEW: "समीक्षा", stagePAYMENT: "भुगतान", stageSUBMISSION: "जमा करना", stageCOMPLETE: "पूर्ण" },
  mr: { startingApplication: "अर्ज सुरू होत आहे…", applyForService: "{name} साठी अर्ज करा", applicationStartedMessage: "तुमचा अर्ज सुरू झाला आहे. अजून काय आवश्यक आहे ते खाली दिले आहे.", applicationResumedMessage: "तुमचा विद्यमान मसुदा सापडला आणि पुन्हा सुरू केला.", applicationProgress: "अर्जाची प्रगती", applicationInProgress: "अर्ज प्रगतीपथावर", profileInformation: "प्रोफाइल माहिती", completeStatus: "पूर्ण", pendingStatus: "प्रलंबित", readyStatus: "तयार", notReadyStatus: "तयार नाही", missingCount: "{count} बाकी", noPaymentRequired: "भरणा आवश्यक नाही", nextStage: "पुढे: {stage}", stagePROFILE: "प्रोफाइल", stageADDITIONAL_INFORMATION: "अतिरिक्त माहिती", stageDOCUMENTS: "कागदपत्रे", stageCONSENT: "संमती", stageREVIEW: "पुनरावलोकन", stagePAYMENT: "भरणा", stageSUBMISSION: "सादरीकरण", stageCOMPLETE: "पूर्ण" },
  kn: { startingApplication: "ಅರ್ಜಿ ಪ್ರಾರಂಭಿಸಲಾಗುತ್ತಿದೆ…", applyForService: "{name} ಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ", applicationStartedMessage: "ನಿಮ್ಮ ಅರ್ಜಿ ಪ್ರಾರಂಭವಾಗಿದೆ. ಇನ್ನೂ ಅಗತ್ಯವಿರುವುದು ಇಲ್ಲಿದೆ.", applicationResumedMessage: "ನಿಮ್ಮ ಹಿಂದಿನ ಕರಡು ಕಂಡುಬಂದಿದೆ ಮತ್ತು ಮುಂದುವರಿಸಲಾಗಿದೆ.", applicationProgress: "ಅರ್ಜಿಯ ಪ್ರಗತಿ", applicationInProgress: "ಅರ್ಜಿ ಪ್ರಗತಿಯಲ್ಲಿದೆ", profileInformation: "ಪ್ರೊಫೈಲ್ ಮಾಹಿತಿ", completeStatus: "ಪೂರ್ಣ", pendingStatus: "ಬಾಕಿ", readyStatus: "ಸಿದ್ಧ", notReadyStatus: "ಸಿದ್ಧವಾಗಿಲ್ಲ", missingCount: "{count} ಬಾಕಿ", noPaymentRequired: "ಪಾವತಿ ಅಗತ್ಯವಿಲ್ಲ", nextStage: "ಮುಂದೆ: {stage}", stagePROFILE: "ಪ್ರೊಫೈಲ್", stageADDITIONAL_INFORMATION: "ಹೆಚ್ಚುವರಿ ಮಾಹಿತಿ", stageDOCUMENTS: "ದಾಖಲೆಗಳು", stageCONSENT: "ಒಪ್ಪಿಗೆ", stageREVIEW: "ಪರಿಶೀಲನೆ", stagePAYMENT: "ಪಾವತಿ", stageSUBMISSION: "ಸಲ್ಲಿಕೆ", stageCOMPLETE: "ಪೂರ್ಣ" },
  ta: { startingApplication: "விண்ணப்பம் தொடங்கப்படுகிறது…", applyForService: "{name} சேவைக்கு விண்ணப்பிக்கவும்", applicationStartedMessage: "உங்கள் விண்ணப்பம் தொடங்கப்பட்டது. இன்னும் தேவையானவை இங்கே.", applicationResumedMessage: "உங்கள் ஏற்கனவே உள்ள வரைவு கண்டறியப்பட்டு தொடரப்பட்டது.", applicationProgress: "விண்ணப்ப முன்னேற்றம்", applicationInProgress: "விண்ணப்பம் நடைபெறுகிறது", profileInformation: "சுயவிவரத் தகவல்", completeStatus: "முடிந்தது", pendingStatus: "நிலுவையில்", readyStatus: "தயார்", notReadyStatus: "தயாராகவில்லை", missingCount: "{count} தேவை", noPaymentRequired: "கட்டணம் தேவையில்லை", nextStage: "அடுத்து: {stage}", stagePROFILE: "சுயவிவரம்", stageADDITIONAL_INFORMATION: "கூடுதல் தகவல்", stageDOCUMENTS: "ஆவணங்கள்", stageCONSENT: "ஒப்புதல்", stageREVIEW: "மதிப்பாய்வு", stagePAYMENT: "கட்டணம்", stageSUBMISSION: "சமர்ப்பித்தல்", stageCOMPLETE: "முடிந்தது" },
  te: { startingApplication: "దరఖాస్తు ప్రారంభిస్తోంది…", applyForService: "{name} కోసం దరఖాస్తు చేయండి", applicationStartedMessage: "మీ దరఖాస్తు ప్రారంభమైంది. ఇంకా కావాల్సినవి ఇక్కడ ఉన్నాయి.", applicationResumedMessage: "మీ ప్రస్తుత ముసాయిదా కనుగొనబడి కొనసాగించబడింది.", applicationProgress: "దరఖాస్తు పురోగతి", applicationInProgress: "దరఖాస్తు పురోగతిలో ఉంది", profileInformation: "ప్రొఫైల్ సమాచారం", completeStatus: "పూర్తి", pendingStatus: "పెండింగ్", readyStatus: "సిద్ధం", notReadyStatus: "సిద్ధంగా లేదు", missingCount: "{count} మిగిలాయి", noPaymentRequired: "చెల్లింపు అవసరం లేదు", nextStage: "తదుపరి: {stage}", stagePROFILE: "ప్రొఫైల్", stageADDITIONAL_INFORMATION: "అదనపు సమాచారం", stageDOCUMENTS: "పత్రాలు", stageCONSENT: "సమ్మతి", stageREVIEW: "సమీక్ష", stagePAYMENT: "చెల్లింపు", stageSUBMISSION: "సమర్పణ", stageCOMPLETE: "పూర్తి" },
  bn: { startingApplication: "আবেদন শুরু হচ্ছে…", applyForService: "{name}-এর জন্য আবেদন করুন", applicationStartedMessage: "আপনার আবেদন শুরু হয়েছে। এখনও যা প্রয়োজন তা নিচে দেওয়া হলো।", applicationResumedMessage: "আপনার আগের খসড়া পাওয়া গেছে এবং আবার শুরু করা হয়েছে।", applicationProgress: "আবেদনের অগ্রগতি", applicationInProgress: "আবেদন প্রক্রিয়াধীন", profileInformation: "প্রোফাইল তথ্য", completeStatus: "সম্পূর্ণ", pendingStatus: "অপেক্ষমাণ", readyStatus: "প্রস্তুত", notReadyStatus: "প্রস্তুত নয়", missingCount: "{count}টি বাকি", noPaymentRequired: "অর্থপ্রদান প্রয়োজন নেই", nextStage: "পরবর্তী: {stage}", stagePROFILE: "প্রোফাইল", stageADDITIONAL_INFORMATION: "অতিরিক্ত তথ্য", stageDOCUMENTS: "নথি", stageCONSENT: "সম্মতি", stageREVIEW: "পর্যালোচনা", stagePAYMENT: "অর্থপ্রদান", stageSUBMISSION: "জমা", stageCOMPLETE: "সম্পূর্ণ" },
} as const;

export const phase3ChatbotUi = {
  en: { saveAnswer: "Save answer", answerSaved: "Answer saved", savingAnswer: "Saving answer…", validValueError: "Please enter a valid value.", selectOption: "Select an option", required: "Required", answerForField: "{field}: {value}", answerSavedMessage: "Answer saved. Here is the next question.", additionalInformationComplete: "Your additional information is complete." },
  hi: { saveAnswer: "उत्तर सहेजें", answerSaved: "उत्तर सहेजा गया", savingAnswer: "उत्तर सहेजा जा रहा है…", validValueError: "कृपया मान्य मान दर्ज करें।", selectOption: "एक विकल्प चुनें", required: "आवश्यक", answerForField: "{field}: {value}", answerSavedMessage: "उत्तर सहेजा गया। अगला प्रश्न यहाँ है।", additionalInformationComplete: "आपकी अतिरिक्त जानकारी पूरी हो गई है।" },
  mr: { saveAnswer: "उत्तर जतन करा", answerSaved: "उत्तर जतन झाले", savingAnswer: "उत्तर जतन होत आहे…", validValueError: "कृपया वैध मूल्य प्रविष्ट करा.", selectOption: "पर्याय निवडा", required: "आवश्यक", answerForField: "{field}: {value}", answerSavedMessage: "उत्तर जतन झाले. पुढील प्रश्न येथे आहे.", additionalInformationComplete: "तुमची अतिरिक्त माहिती पूर्ण झाली आहे." },
  kn: { saveAnswer: "ಉತ್ತರ ಉಳಿಸಿ", answerSaved: "ಉತ್ತರ ಉಳಿಸಲಾಗಿದೆ", savingAnswer: "ಉತ್ತರ ಉಳಿಸಲಾಗುತ್ತಿದೆ…", validValueError: "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಮೌಲ್ಯವನ್ನು ನಮೂದಿಸಿ.", selectOption: "ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ", required: "ಅಗತ್ಯ", answerForField: "{field}: {value}", answerSavedMessage: "ಉತ್ತರ ಉಳಿಸಲಾಗಿದೆ. ಮುಂದಿನ ಪ್ರಶ್ನೆ ಇಲ್ಲಿದೆ.", additionalInformationComplete: "ನಿಮ್ಮ ಹೆಚ್ಚುವರಿ ಮಾಹಿತಿ ಪೂರ್ಣವಾಗಿದೆ." },
  ta: { saveAnswer: "பதிலைச் சேமிக்கவும்", answerSaved: "பதில் சேமிக்கப்பட்டது", savingAnswer: "பதில் சேமிக்கப்படுகிறது…", validValueError: "சரியான மதிப்பை உள்ளிடவும்.", selectOption: "ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்", required: "தேவை", answerForField: "{field}: {value}", answerSavedMessage: "பதில் சேமிக்கப்பட்டது. அடுத்த கேள்வி இதோ.", additionalInformationComplete: "உங்கள் கூடுதல் தகவல் முடிந்தது." },
  te: { saveAnswer: "సమాధానాన్ని సేవ్ చేయండి", answerSaved: "సమాధానం సేవ్ అయింది", savingAnswer: "సమాధానం సేవ్ అవుతోంది…", validValueError: "దయచేసి సరైన విలువను నమోదు చేయండి.", selectOption: "ఒక ఎంపికను ఎంచుకోండి", required: "అవసరం", answerForField: "{field}: {value}", answerSavedMessage: "సమాధానం సేవ్ అయింది. తదుపరి ప్రశ్న ఇక్కడ ఉంది.", additionalInformationComplete: "మీ అదనపు సమాచారం పూర్తయింది." },
  bn: { saveAnswer: "উত্তর সংরক্ষণ করুন", answerSaved: "উত্তর সংরক্ষিত", savingAnswer: "উত্তর সংরক্ষণ হচ্ছে…", validValueError: "একটি বৈধ মান লিখুন।", selectOption: "একটি বিকল্প বেছে নিন", required: "আবশ্যক", answerForField: "{field}: {value}", answerSavedMessage: "উত্তর সংরক্ষিত। পরবর্তী প্রশ্নটি এখানে।", additionalInformationComplete: "আপনার অতিরিক্ত তথ্য সম্পূর্ণ হয়েছে।" },
} as const;

export const applicationUi = {
  kn: { applicationsDescription: "ನಿಮ್ಮ ಅರ್ಜಿಗಳನ್ನು ಗಮನಿಸಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ.", searchApplications: "ಅರ್ಜಿಗಳನ್ನು ಹುಡುಕಿ", filterApplications: "ಅರ್ಜಿಗಳನ್ನು ಫಿಲ್ಟರ್ ಮಾಡಿ", all: "ಎಲ್ಲಾ", draft: "ಕರಡು", submitted: "ಸಲ್ಲಿಸಲಾಗಿದೆ", applicationColumn: "ಅರ್ಜಿ", updated: "ನವೀಕರಿಸಲಾಗಿದೆ", status: "ಸ್ಥಿತಿ", action: "ಕ್ರಮ", view: "ನೋಡಿ", deleteDraft: "ಕರಡು ಅಳಿಸಿ", deleting: "ಅಳಿಸಲಾಗುತ್ತಿದೆ…", noApplications: "ಯಾವುದೇ ಅರ್ಜಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ.", noDraftApplications: "ಕರಡು ಅರ್ಜಿಗಳಿಲ್ಲ", noDraftApplicationsDescription: "ಪೂರ್ಣಗೊಳಿಸಲು ಕಾಯುತ್ತಿರುವ ಅರ್ಜಿಗಳಿಲ್ಲ.", noSubmittedApplications: "ಸಲ್ಲಿಸಿದ ಅರ್ಜಿಗಳಿಲ್ಲ", noSubmittedApplicationsDescription: "ಸಲ್ಲಿಸಿದ ಅರ್ಜಿಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.", noApplicationsYet: "ಇನ್ನೂ ಅರ್ಜಿಗಳಿಲ್ಲ", noApplicationsYetDescription: "ಮೊದಲ ಅರ್ಜಿಯನ್ನು ಆರಂಭಿಸಲು ಸರ್ಕಾರಿ ಸೇವೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ.", changeApplicationSearch: "ಹುಡುಕಾಟ ಅಥವಾ ಫಿಲ್ಟರ್ ಬದಲಿಸಿ.", loadingApplications: "ನಿಮ್ಮ ಅರ್ಜಿಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ…", needsAttention: "ನಿಮ್ಮ ಗಮನ ಅಗತ್ಯ", applicationHistory: "ಅರ್ಜಿ ಇತಿಹಾಸ", deleteDraftTitle: "ಕರಡನ್ನು ಅಳಿಸಬೇಕೆ?", deleteDraftDescription: "ಈ ಕರಡು ಮತ್ತು ಉಳಿಸಿದ ಉತ್ತರಗಳನ್ನು ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲಾಗುತ್ತದೆ.", deleteDraftError: "ಈ ಕರಡನ್ನು ಅಳಿಸಲಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", moreActions: "{name} ಗಾಗಿ ಹೆಚ್ಚಿನ ಕ್ರಮಗಳು" },
  ta: { applicationsDescription: "உங்கள் விண்ணப்பங்களைக் கண்காணித்து நிர்வகிக்கவும்.", searchApplications: "விண்ணப்பங்களைத் தேடுக", filterApplications: "விண்ணப்பங்களை வடிகட்டுக", all: "அனைத்தும்", draft: "வரைவு", submitted: "சமர்ப்பிக்கப்பட்டது", applicationColumn: "விண்ணப்பம்", updated: "புதுப்பிக்கப்பட்டது", status: "நிலை", action: "செயல்", view: "காண்க", deleteDraft: "வரைவை நீக்குக", deleting: "நீக்கப்படுகிறது…", noApplications: "விண்ணப்பங்கள் எதுவும் இல்லை.", noDraftApplications: "வரைவு விண்ணப்பங்கள் இல்லை", noDraftApplicationsDescription: "முடிக்கக் காத்திருக்கும் விண்ணப்பங்கள் இல்லை.", noSubmittedApplications: "சமர்ப்பிக்கப்பட்ட விண்ணப்பங்கள் இல்லை", noSubmittedApplicationsDescription: "சமர்ப்பிக்கப்பட்ட விண்ணப்பங்கள் இங்கே தோன்றும்.", noApplicationsYet: "இன்னும் விண்ணப்பங்கள் இல்லை", noApplicationsYetDescription: "முதல் விண்ணப்பத்தைத் தொடங்க அரசு சேவைகளைப் பாருங்கள்.", changeApplicationSearch: "தேடல் அல்லது வடிகட்டியை மாற்றவும்.", loadingApplications: "உங்கள் விண்ணப்பங்கள் ஏற்றப்படுகின்றன…", needsAttention: "உங்கள் கவனம் தேவை", applicationHistory: "விண்ணப்ப வரலாறு", deleteDraftTitle: "வரைவை நீக்கவா?", deleteDraftDescription: "இந்த வரைவும் சேமித்த பதில்களும் நிரந்தரமாக நீக்கப்படும்.", deleteDraftError: "இந்த வரைவை நீக்க முடியவில்லை. மீண்டும் முயலுங்கள்.", moreActions: "{name} க்கான கூடுதல் செயல்கள்" },
  te: { applicationsDescription: "మీ దరఖాస్తులను ట్రాక్ చేసి నిర్వహించండి.", searchApplications: "దరఖాస్తులను వెతకండి", filterApplications: "దరఖాస్తులను వడపోయండి", all: "అన్నీ", draft: "ముసాయిదా", submitted: "సమర్పించబడింది", applicationColumn: "దరఖాస్తు", updated: "నవీకరించబడింది", status: "స్థితి", action: "చర్య", view: "చూడండి", deleteDraft: "ముసాయిదాను తొలగించండి", deleting: "తొలగిస్తోంది…", noApplications: "దరఖాస్తులు కనుగొనబడలేదు.", noDraftApplications: "ముసాయిదా దరఖాస్తులు లేవు", noDraftApplicationsDescription: "పూర్తి చేయాల్సిన దరఖాస్తులు లేవు.", noSubmittedApplications: "సమర్పించిన దరఖాస్తులు లేవు", noSubmittedApplicationsDescription: "సమర్పించిన దరఖాస్తులు ఇక్కడ కనిపిస్తాయి.", noApplicationsYet: "ఇంకా దరఖాస్తులు లేవు", noApplicationsYetDescription: "మొదటి దరఖాస్తును ప్రారంభించడానికి ప్రభుత్వ సేవలను చూడండి.", changeApplicationSearch: "శోధన లేదా ఫిల్టర్‌ను మార్చండి.", loadingApplications: "మీ దరఖాస్తులు లోడ్ అవుతున్నాయి…", needsAttention: "మీ దృష్టి అవసరం", applicationHistory: "దరఖాస్తు చరిత్ర", deleteDraftTitle: "ముసాయిదాను తొలగించాలా?", deleteDraftDescription: "ఈ ముసాయిదా మరియు సేవ్ చేసిన సమాధానాలు శాశ్వతంగా తొలగించబడతాయి.", deleteDraftError: "ఈ ముసాయిదాను తొలగించలేకపోయాం. మళ్లీ ప్రయత్నించండి.", moreActions: "{name} కోసం మరిన్ని చర్యలు" },
  bn: { applicationsDescription: "আপনার আবেদনগুলি অনুসরণ ও পরিচালনা করুন।", searchApplications: "আবেদন খুঁজুন", filterApplications: "আবেদন ফিল্টার করুন", all: "সব", draft: "খসড়া", submitted: "জমা দেওয়া হয়েছে", applicationColumn: "আবেদন", updated: "হালনাগাদ", status: "অবস্থা", action: "কাজ", view: "দেখুন", deleteDraft: "খসড়া মুছুন", deleting: "মোছা হচ্ছে…", noApplications: "কোনো আবেদন পাওয়া যায়নি।", noDraftApplications: "কোনো খসড়া আবেদন নেই", noDraftApplicationsDescription: "সম্পূর্ণ করার অপেক্ষায় কোনো আবেদন নেই।", noSubmittedApplications: "জমা দেওয়া আবেদন নেই", noSubmittedApplicationsDescription: "জমা দেওয়া আবেদন এখানে দেখা যাবে।", noApplicationsYet: "এখনও কোনো আবেদন নেই", noApplicationsYetDescription: "প্রথম আবেদন শুরু করতে সরকারি পরিষেবা দেখুন।", changeApplicationSearch: "অনুসন্ধান বা ফিল্টার পরিবর্তন করুন।", loadingApplications: "আপনার আবেদন লোড হচ্ছে…", needsAttention: "আপনার মনোযোগ প্রয়োজন", applicationHistory: "আবেদনের ইতিহাস", deleteDraftTitle: "খসড়া মুছবেন?", deleteDraftDescription: "এই খসড়া ও সংরক্ষিত উত্তর স্থায়ীভাবে মুছে যাবে।", deleteDraftError: "এই খসড়া মোছা যায়নি। আবার চেষ্টা করুন।", moreActions: "{name}-এর জন্য আরও কাজ" }
} as const;

export const deadlineUi = {
  hi: { submissionDate: "जमा करने की तारीख", applicationDeadline: "आवेदन की अंतिम तिथि" },
  mr: { submissionDate: "सादर करण्याची तारीख", applicationDeadline: "अर्जाची अंतिम तारीख" },
  kn: { submissionDate: "ಸಲ್ಲಿಕೆ ದಿನಾಂಕ", applicationDeadline: "ಅರ್ಜಿ ಸಲ್ಲಿಸುವ ಅಂತಿಮ ದಿನಾಂಕ" },
  ta: { submissionDate: "சமர்ப்பித்த தேதி", applicationDeadline: "விண்ணப்பத்தின் கடைசி தேதி" },
  te: { submissionDate: "సమర్పణ తేదీ", applicationDeadline: "దరఖాస్తు చివరి తేదీ" },
  bn: { submissionDate: "জমা দেওয়ার তারিখ", applicationDeadline: "আবেদনের শেষ তারিখ" },
} as const;

export const statusUi = {
  kn: { statusDRAFT: "ಕರಡು", statusADDITIONAL_INFO_REQUIRED: "ಹೆಚ್ಚುವರಿ ಮಾಹಿತಿ ಅಗತ್ಯ", statusCONSENT_REQUIRED: "ಒಪ್ಪಿಗೆ ಅಗತ್ಯ", statusREADY_FOR_REVIEW: "ಪರಿಶೀಲನೆಗೆ ಸಿದ್ಧ", statusPAYMENT_REQUIRED: "ಪಾವತಿ ಅಗತ್ಯ", statusSUBMITTED: "ಸಲ್ಲಿಸಲಾಗಿದೆ", statusPROCESSING: "ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ", statusCOMPLETED: "ಪೂರ್ಣಗೊಂಡಿದೆ", statusREJECTED: "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ", statusCANCELLED: "ರದ್ದುಪಡಿಸಲಾಗಿದೆ" },
  ta: { statusDRAFT: "வரைவு", statusADDITIONAL_INFO_REQUIRED: "கூடுதல் தகவல் தேவை", statusCONSENT_REQUIRED: "ஒப்புதல் தேவை", statusREADY_FOR_REVIEW: "மதிப்பாய்வுக்குத் தயார்", statusPAYMENT_REQUIRED: "கட்டணம் தேவை", statusSUBMITTED: "சமர்ப்பிக்கப்பட்டது", statusPROCESSING: "செயலாக்கத்தில்", statusCOMPLETED: "முடிந்தது", statusREJECTED: "நிராகரிக்கப்பட்டது", statusCANCELLED: "ரத்துசெய்யப்பட்டது" },
  te: { statusDRAFT: "ముసాయిదా", statusADDITIONAL_INFO_REQUIRED: "అదనపు సమాచారం అవసరం", statusCONSENT_REQUIRED: "సమ్మతి అవసరం", statusREADY_FOR_REVIEW: "సమీక్షకు సిద్ధం", statusPAYMENT_REQUIRED: "చెల్లింపు అవసరం", statusSUBMITTED: "సమర్పించబడింది", statusPROCESSING: "ప్రాసెస్‌లో ఉంది", statusCOMPLETED: "పూర్తయింది", statusREJECTED: "తిరస్కరించబడింది", statusCANCELLED: "రద్దు చేయబడింది" },
  bn: { statusDRAFT: "খসড়া", statusADDITIONAL_INFO_REQUIRED: "অতিরিক্ত তথ্য প্রয়োজন", statusCONSENT_REQUIRED: "সম্মতি প্রয়োজন", statusREADY_FOR_REVIEW: "পর্যালোচনার জন্য প্রস্তুত", statusPAYMENT_REQUIRED: "অর্থপ্রদান প্রয়োজন", statusSUBMITTED: "জমা দেওয়া হয়েছে", statusPROCESSING: "প্রক্রিয়াধীন", statusCOMPLETED: "সম্পূর্ণ", statusREJECTED: "প্রত্যাখ্যাত", statusCANCELLED: "বাতিল" }
} as const;

export const jurisdictionUi = {
  kn: { servicesFor: "ಇವರಿಗಾಗಿ ಸೇವೆಗಳು", selectState: "ರಾಜ್ಯ ಅಥವಾ ವ್ಯಾಪ್ತಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ", centralGovernmentServices: "ಕೇಂದ್ರ ಸರ್ಕಾರದ ಸೇವೆಗಳು", stateGovernmentServices: "{state} ಸರ್ಕಾರದ ಸೇವೆಗಳು", centralGovernment: "ಕೇಂದ್ರ ಸರ್ಕಾರ", stateGovernment: "ರಾಜ್ಯ ಸರ್ಕಾರ", governmentLevel: "ಸರ್ಕಾರದ ಹಂತ", jurisdiction: "ವ್ಯಾಪ್ತಿ", noServicesForState: "{state} ಗಾಗಿ ಹೊಂದುವ ಸೇವೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.", nationalEntranceExams: "ರಾಷ್ಟ್ರೀಯ ಪ್ರವೇಶ ಪರೀಕ್ಷೆಗಳು" },
  ta: { servicesFor: "இதற்கான சேவைகள்", selectState: "மாநிலம் அல்லது அதிகார வரம்பைத் தேர்ந்தெடுக்கவும்", centralGovernmentServices: "மத்திய அரசு சேவைகள்", stateGovernmentServices: "{state} அரசு சேவைகள்", centralGovernment: "மத்திய அரசு", stateGovernment: "மாநில அரசு", governmentLevel: "அரசு நிலை", jurisdiction: "அதிகார வரம்பு", noServicesForState: "{state} க்குப் பொருந்தும் சேவைகள் எதுவும் இல்லை.", nationalEntranceExams: "தேசிய நுழைவுத் தேர்வுகள்" },
  te: { servicesFor: "వీరి కోసం సేవలు", selectState: "రాష్ట్రం లేదా అధికార పరిధిని ఎంచుకోండి", centralGovernmentServices: "కేంద్ర ప్రభుత్వ సేవలు", stateGovernmentServices: "{state} ప్రభుత్వ సేవలు", centralGovernment: "కేంద్ర ప్రభుత్వం", stateGovernment: "రాష్ట్ర ప్రభుత్వం", governmentLevel: "ప్రభుత్వ స్థాయి", jurisdiction: "అధికార పరిధి", noServicesForState: "{state} కోసం సరిపోలే సేవలు లేవు.", nationalEntranceExams: "జాతీయ ప్రవేశ పరీక్షలు" },
  bn: { servicesFor: "এর জন্য পরিষেবা", selectState: "রাজ্য বা অধিক্ষেত্র নির্বাচন করুন", centralGovernmentServices: "কেন্দ্রীয় সরকারের পরিষেবা", stateGovernmentServices: "{state} সরকারের পরিষেবা", centralGovernment: "কেন্দ্রীয় সরকার", stateGovernment: "রাজ্য সরকার", governmentLevel: "সরকারের স্তর", jurisdiction: "অধিক্ষেত্র", noServicesForState: "{state}-এর জন্য কোনো মিলে যাওয়া পরিষেবা নেই।", nationalEntranceExams: "জাতীয় প্রবেশিকা পরীক্ষা" },
} as const;

// Shared UI copy. Unlisted strings deliberately fall back to English.
export const regionalDictionaries = {
  bn: { dashboard: "ড্যাশবোর্ড", profile: "আমার প্রোফাইল", services: "সরকারি পরিষেবা", applications: "আমার আবেদন", documents: "আমার নথি", settings: "সেটিংস", save: "সংরক্ষণ করুন", cancel: "বাতিল", continue: "চালিয়ে যান", back: "ফিরে যান", loading: "লোড হচ্ছে…", language: "ভাষা", editProfile: "প্রোফাইল সম্পাদনা করুন", notProvided: "প্রদত্ত নয়", yes: "হ্যাঁ", no: "না", personalDetails: "ব্যক্তিগত বিবরণ", contactDetails: "যোগাযোগের বিবরণ", parentsDetails: "অভিভাবকের বিবরণ", socialDetails: "সামাজিক / সংরক্ষণ বিবরণ", basicEducation: "প্রাথমিক শিক্ষা", otherDetails: "অন্যান্য সাধারণ বিবরণ", address: "ঠিকানা", permanentAddress: "স্থায়ী ঠিকানা", currentAddress: "বর্তমান ঠিকানা", searchServices: "পরিষেবা খুঁজুন", allServices: "সব পরিষেবা", category: "বিভাগ", viewDetails: "বিস্তারিত দেখুন", applyNow: "এখনই আবেদন করুন", whatYouNeed: "যা প্রয়োজন", fromProfile: "আপনার প্রোফাইল থেকে", additionalInformation: "অতিরিক্ত তথ্য", free: "বিনামূল্যে", noApplicationFee: "কোনো আবেদন ফি নেই", loadingServices: "পরিষেবা লোড হচ্ছে…", noServicesFound: "কোনো পরিষেবা পাওয়া যায়নি", changeSearch: "অনুসন্ধান বা বিভাগ পরিবর্তন করে দেখুন।", reviewApplication: "আবেদন পর্যালোচনা করুন", upload: "আপলোড", next: "পরবর্তী" },
  gu: { dashboard: "ડૅશબોર્ડ", profile: "મારી પ્રોફાઇલ", services: "સરકારી સેવાઓ", applications: "મારી અરજીઓ", documents: "મારા દસ્તાવેજો", settings: "સેટિંગ્સ", save: "સાચવો", cancel: "રદ કરો", continue: "ચાલુ રાખો", back: "પાછા", loading: "લોડ થઈ રહ્યું છે…", language: "ભાષા" },
  kn: { dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", profile: "ನನ್ನ ಪ್ರೊಫೈಲ್", services: "ಸರ್ಕಾರಿ ಸೇವೆಗಳು", applications: "ನನ್ನ ಅರ್ಜಿಗಳು", documents: "ನನ್ನ ದಾಖಲೆಗಳು", settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು", save: "ಉಳಿಸಿ", cancel: "ರದ್ದುಮಾಡಿ", continue: "ಮುಂದುವರಿಸಿ", back: "ಹಿಂದೆ", loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ…", language: "ಭಾಷೆ", editProfile: "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ", notProvided: "ಒದಗಿಸಲಾಗಿಲ್ಲ", yes: "ಹೌದು", no: "ಇಲ್ಲ", personalDetails: "ವೈಯಕ್ತಿಕ ವಿವರಗಳು", contactDetails: "ಸಂಪರ್ಕ ವಿವರಗಳು", parentsDetails: "ಪೋಷಕರ ವಿವರಗಳು", socialDetails: "ಸಾಮಾಜಿಕ / ಮೀಸಲಾತಿ ವಿವರಗಳು", basicEducation: "ಮೂಲ ಶಿಕ್ಷಣ", otherDetails: "ಇತರೆ ಸಾಮಾನ್ಯ ವಿವರಗಳು", address: "ವಿಳಾಸ", permanentAddress: "ಶಾಶ್ವತ ವಿಳಾಸ", currentAddress: "ಪ್ರಸ್ತುತ ವಿಳಾಸ", searchServices: "ಸೇವೆಗಳನ್ನು ಹುಡುಕಿ", allServices: "ಎಲ್ಲಾ ಸೇವೆಗಳು", category: "ವರ್ಗ", viewDetails: "ವಿವರಗಳನ್ನು ನೋಡಿ", applyNow: "ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ", whatYouNeed: "ನಿಮಗೆ ಬೇಕಾಗಿರುವುದು", fromProfile: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ನಿಂದ", additionalInformation: "ಹೆಚ್ಚುವರಿ ಮಾಹಿತಿ", free: "ಉಚಿತ", noApplicationFee: "ಅರ್ಜಿ ಶುಲ್ಕವಿಲ್ಲ", loadingServices: "ಸೇವೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ…", noServicesFound: "ಯಾವುದೇ ಸೇವೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ", changeSearch: "ಹುಡುಕಾಟ ಅಥವಾ ವರ್ಗವನ್ನು ಬದಲಿಸಿ.", reviewApplication: "ಅರ್ಜಿಯನ್ನು ಪರಿಶೀಲಿಸಿ", upload: "ಅಪ್‌ಲೋಡ್", next: "ಮುಂದೆ" },
  ml: { dashboard: "ഡാഷ്ബോർഡ്", profile: "എന്റെ പ്രൊഫൈൽ", services: "സർക്കാർ സേവനങ്ങൾ", applications: "എന്റെ അപേക്ഷകൾ", documents: "എന്റെ രേഖകൾ", settings: "ക്രമീകരണങ്ങൾ", save: "സംരക്ഷിക്കുക", cancel: "റദ്ദാക്കുക", continue: "തുടരുക", back: "തിരികെ", loading: "ലോഡ് ചെയ്യുന്നു…", language: "ഭാഷ" },
  mr: { dashboard: "डॅशबोर्ड", profile: "माझे प्रोफाइल", services: "शासकीय सेवा", applications: "माझे अर्ज", documents: "माझी कागदपत्रे", settings: "सेटिंग्ज", save: "जतन करा", cancel: "रद्द करा", continue: "सुरू ठेवा", back: "मागे", loading: "लोड होत आहे…", language: "भाषा" },
  pa: { dashboard: "ਡੈਸ਼ਬੋਰਡ", profile: "ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ", services: "ਸਰਕਾਰੀ ਸੇਵਾਵਾਂ", applications: "ਮੇਰੀਆਂ ਅਰਜ਼ੀਆਂ", documents: "ਮੇਰੇ ਦਸਤਾਵੇਜ਼", settings: "ਸੈਟਿੰਗਾਂ", save: "ਸੰਭਾਲੋ", cancel: "ਰੱਦ ਕਰੋ", continue: "ਜਾਰੀ ਰੱਖੋ", back: "ਵਾਪਸ", loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…", language: "ਭਾਸ਼ਾ" },
  ta: { dashboard: "டாஷ்போர்டு", profile: "என் சுயவிவரம்", services: "அரசு சேவைகள்", applications: "என் விண்ணப்பங்கள்", documents: "என் ஆவணங்கள்", settings: "அமைப்புகள்", save: "சேமிக்கவும்", cancel: "ரத்துசெய்", continue: "தொடரவும்", back: "பின்னால்", loading: "ஏற்றுகிறது…", language: "மொழி", editProfile: "சுயவிவரத்தைத் திருத்து", notProvided: "வழங்கப்படவில்லை", yes: "ஆம்", no: "இல்லை", personalDetails: "தனிப்பட்ட விவரங்கள்", contactDetails: "தொடர்பு விவரங்கள்", parentsDetails: "பெற்றோர் விவரங்கள்", socialDetails: "சமூக / இடஒதுக்கீடு விவரங்கள்", basicEducation: "அடிப்படைக் கல்வி", otherDetails: "பிற பொதுவான விவரங்கள்", address: "முகவரி", permanentAddress: "நிரந்தர முகவரி", currentAddress: "தற்போதைய முகவரி", searchServices: "சேவைகளைத் தேடுக", allServices: "அனைத்து சேவைகள்", category: "வகை", viewDetails: "விவரங்களைக் காண்க", applyNow: "இப்போது விண்ணப்பிக்கவும்", whatYouNeed: "உங்களுக்குத் தேவையானவை", fromProfile: "உங்கள் சுயவிவரத்திலிருந்து", additionalInformation: "கூடுதல் தகவல்", free: "இலவசம்", noApplicationFee: "விண்ணப்பக் கட்டணம் இல்லை", loadingServices: "சேவைகள் ஏற்றப்படுகின்றன…", noServicesFound: "சேவைகள் எதுவும் கிடைக்கவில்லை", changeSearch: "தேடல் அல்லது வகையை மாற்றிப் பாருங்கள்.", reviewApplication: "விண்ணப்பத்தை மதிப்பாய்வு செய்க", upload: "பதிவேற்றுக", next: "அடுத்து" },
  te: { dashboard: "డాష్‌బోర్డ్", profile: "నా ప్రొఫైల్", services: "ప్రభుత్వ సేవలు", applications: "నా దరఖాస్తులు", documents: "నా పత్రాలు", settings: "సెట్టింగ్‌లు", save: "సేవ్ చేయండి", cancel: "రద్దు చేయండి", continue: "కొనసాగించండి", back: "వెనుకకు", loading: "లోడ్ అవుతోంది…", language: "భాష", editProfile: "ప్రొఫైల్ సవరించండి", notProvided: "అందించబడలేదు", yes: "అవును", no: "కాదు", personalDetails: "వ్యక్తిగత వివరాలు", contactDetails: "సంప్రదింపు వివరాలు", parentsDetails: "తల్లిదండ్రుల వివరాలు", socialDetails: "సామాజిక / రిజర్వేషన్ వివరాలు", basicEducation: "ప్రాథమిక విద్య", otherDetails: "ఇతర సాధారణ వివరాలు", address: "చిరునామా", permanentAddress: "శాశ్వత చిరునామా", currentAddress: "ప్రస్తుత చిరునామా", searchServices: "సేవలను వెతకండి", allServices: "అన్ని సేవలు", category: "వర్గం", viewDetails: "వివరాలు చూడండి", applyNow: "ఇప్పుడే దరఖాస్తు చేయండి", whatYouNeed: "మీకు కావలసినవి", fromProfile: "మీ ప్రొఫైల్ నుండి", additionalInformation: "అదనపు సమాచారం", free: "ఉచితం", noApplicationFee: "దరఖాస్తు రుసుము లేదు", loadingServices: "సేవలు లోడ్ అవుతున్నాయి…", noServicesFound: "సేవలు కనుగొనబడలేదు", changeSearch: "శోధన లేదా వర్గాన్ని మార్చండి.", reviewApplication: "దరఖాస్తును సమీక్షించండి", upload: "అప్‌లోడ్", next: "తదుపరి" },
  ur: { dashboard: "ڈیش بورڈ", profile: "میرا پروفائل", services: "سرکاری خدمات", applications: "میری درخواستیں", documents: "میرے دستاویزات", settings: "ترتیبات", save: "محفوظ کریں", cancel: "منسوخ کریں", continue: "جاری رکھیں", back: "واپس", loading: "لوڈ ہو رہا ہے…", language: "زبان" },
} as const;
